# Generated by Django 5.2.12 on 2026-09-23 12:02

from django.db import migrations, models


def set_first_user_as_owner(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    first_user = User.objects.order_by('pk').first()
    if first_user:
        User.objects.filter(pk=first_user.pk).update(role='owner')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Designates whether the user must set a new password on next login.'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('role',), name='authentication_user_single_owner'),
        ),
        migrations.RunPython(set_first_user_as_owner, migrations.RunPython.noop),
    ]
