# Generated by Django 5.2.12 on 2026-03-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifieddomain',
            name='aws_region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='verifieddomain',
            name='mail_from_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='verifieddomain',
            name='mail_from_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
