# Generated by Django 5.2.12 on 2026-03-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesy', '0002_add_mail_from_and_region_to_verified_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencemember',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
