# Generated by Django 5.2.12 on 2026-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesy', '0004_remove_email_template_add_subject_html_body_to_campaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiencemember',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='sesconfiguration',
            name='config_valid',
            field=models.BooleanField(default=False, help_text='Indicates whether the AWS credentials are valid and reachable'),
        ),
        migrations.AddField(
            model_name='sesconfiguration',
            name='max_sending_rate',
            field=models.FloatField(blank=True, help_text='Max sending rate (emails/sec) retrieved from AWS SES', null=True),
        ),
    ]
